In [1]:
import wandb
import nltk
from nltk.stem.porter import *
from torch.nn import *
from torch.optim import *
import numpy as np
import pandas as pd
import torch,torchvision
import random
from tqdm import *
from torch.utils.data import Dataset,DataLoader
stemmer = PorterStemmer()
PROJECT_NAME = 'NLP-with-Disaster-Tweets-cleaning-data-V3'
device = 'cuda'

In [2]:
def tokenize(sentence):
    return nltk.word_tokenize(sentence.lower())

In [3]:
tokenize("@100")

['@', '100']

In [4]:
def stem(word):
    return stemmer.stem(word.lower())

In [5]:
stem('organic')

'organ'

In [8]:
def bag_of_words(tokenized_words,words):
    tokenized_words = [stem(w) for w in tokenized_words]
    bag = np.zeros(len(words))
    for idx,w in enumerate(words):
        if w in tokenized_words:
            bag[idx] = 1.0
    return bag

In [9]:
bag_of_words(['hi'],['hi','how','hi'])

array([1., 0., 1.])

In [25]:
data = pd.read_csv('./data.csv')[:3250].sample(frac=1)

In [26]:
X = data['text']

In [27]:
data

id              keyword                location  \
2291  3286             demolish              London, UK   
3083  4425          electrocute                     NaN   
1454  2097             casualty   In @4SkinChan 's arms   
1693  2443              collide             Medford, NJ   
922   1335           blown%20up               801 SL,UT   
...    ...                  ...                     ...   
1345  1943  burning%20buildings  New Orleans ,Louisiana   
2573  3690              destroy                  Norway   
1524  2204         catastrophic                 Lurking   
698   1005              blazing                     NaN   
1176  1693    bridge%20collapse                  Boston   

                                                   text  target  
2291  The far right racist  # AvigdorLiberman calls ...       1  
3083  She says that she ' d love to come help but\nT...       0  
1454   @ reriellechan HE WAS THE LICH KING ' S FIRST...       1  
1693   # TheDoolingGroup 2 injured when 2 school bus...       1  
922      Damn greinke got blown up in that first inning       0  
...                                                 ...     ...  
1345             Burning buildings ?  Media outrage ?         1  
2573  Politics  =  Preschool Attitude :  Russia orde...       1  
1524  Pretty much every time the audio dies on an au...       0  
698   I am blazing rn and there is nothing you can d...       0  
1176  Two giant cranes holding a bridge collapse int...       1  

[3250 rows x 5 columns]

In [28]:
y = data['target']

In [29]:
words = []
data = []
labels = {}
labels_r = {}
idx = 0

In [30]:
for label in y.tolist():
    if label not in list(labels.keys()):
        idx += 1
        labels[label] = idx
        labels_r[idx] = label

In [31]:
labels

{1: 1, 0: 2}

In [33]:
for X_batch,y_batch in tqdm(zip(X,y)):
    X_batch = tokenize(X_batch)
    new_X = []
    for Xb in X_batch:
        new_X.append(stem(Xb))
    words.extend(new_X)
    data.append([
        new_X,
        np.eye(labels[y_batch],len(labels))[labels[y_batch]-1]
    ])

3250it [00:00, 3272.09it/s]


In [39]:
words = sorted(set(words))

In [40]:
np.random.shuffle(data)

In [41]:
X = []
y = []

In [42]:
for sentence,tag in tqdm(data):
    X.append(bag_of_words(sentence,words))
    y.append(tag)

100%|██████████| 3250/3250 [00:05<00:00, 609.66it/s]


In [53]:
X[590]

array([0., 0., 0., ..., 0., 0., 0.])

In [54]:
y[0]

array([0., 1.])

In [55]:
from sklearn.model_selection import *
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.125,shuffle=False)
X_train = torch.from_numpy(np.array(X_train)).to(device).float()
y_train = torch.from_numpy(np.array(y_train)).to(device).float()
X_test = torch.from_numpy(np.array(X_test)).to(device).float()
y_test = torch.from_numpy(np.array(y_test)).to(device).float()

In [56]:
def get_loss(model,X,y,criterion):
    preds = model(X)
    loss = criterion(preds,y)
    return loss.item()

In [ ]:
def get_accuracy(model,X,y):
    preds = model(X)
    correct = 0
    total = 0
    for pred,yb in zip(preds,y):
        pred = int(torch.argmax(pred))
        yb = int(torch.argmax(yb))
        if pred == yb:
            correct += 1
        total += 1
    acc = round(correct/total,3)*100
    return acc

In [ ]:
class Model(Module):
    def __init__(self):
        super().__init__()
        self.hidden = 512
        self.activation = ReLU()
        self.linear1 = Linear(len(words),self.hidden)
        self.linear2 = Linear(self.hidden,self.hidden)
        self.linear3 = Linear(self.hidden,len(labels))
    
    def forward(self,X):
        preds = self.linear1(X)
        preds = self.activation(self.linear2(preds))
        preds = self.linear3(preds)
        return preds

In [ ]:
model = Model().to(device)
criterion = MSELoss()
optimizer = Adam(model.parameters(),lr=0.001)
epochs = 100
batch_size = 32

In [ ]:
wandb.init(project=PROJECT_NAME,name='baseline')
for _ in tqdm(range(epochs)):
    for i in range(0,len(X_train),batch_size):
        X_batch = X_train[i:i+batch_size]
        y_batch = y_train[i:i+batch_size]
        preds = model(X_batch)
        loss = criterion(preds,y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    model.eval()
    torch.cuda.empty_cache()
    wandb.log({'Loss':(get_loss(model,X_train,y_train,criterion)+get_loss(model,X_batch,y_batch,criterion)/2)})
    torch.cuda.empty_cache()
    wandb.log({'Val Loss':get_loss(model,X_test,y_test,criterion)})
    torch.cuda.empty_cache()
    wandb.log({'Acc':(get_accuracy(model,X_train,y_train)+get_accuracy(model,X_batch,y_batch))/2})
    torch.cuda.empty_cache()
    wandb.log({'Val Acc':get_accuracy(model,X_test,y_test)})
    torch.cuda.empty_cache()
    model.train()
wandb.finish()

In [ ]:
torch.save(model,'model.pt')
torch.save(model,'model.pth')
torch.save(model.state_dict(),'model-sd.pt')
torch.save(model.state_dict(),'model-sd.pth')
torch.save(X,'X.pt')
torch.save(X,'X.pth')
torch.save(y,'y.pt')
torch.save(y,'y.pth')

In [ ]:
torch.save(X_train,'X_train.pt')
torch.save(X_test,'X_test.pth')
torch.save(y_train,'y_train.pt')
torch.save(y_test,'y_test.pth')

In [ ]:
torch.save(words,'words.pt')
torch.save(words,'words.pth')
torch.save(data,'data.pt')
torch.save(data,'data.pth')
torch.save(labels,'labels.pt')
torch.save(labels,'labels.pth')