In [1]:
import wandb
import nltk
from nltk.stem.porter import *
from torch.nn import *
from torch.optim import *
import numpy as np
import pandas as pd
import torch,torchvision
import random
from tqdm import *
from torch.utils.data import Dataset,DataLoader
stemmer = PorterStemmer()
PROJECT_NAME = 'NLP-with-Disaster-Tweets-cleaning-data-V3'
device = 'cuda'

In [2]:
def tokenize(sentence):
    return nltk.word_tokenize(sentence.lower())

In [3]:
tokenize("@100")

['@', '100']

In [4]:
def stem(word):
    return stemmer.stem(word.lower())

In [5]:
stem('organic')

'organ'

In [6]:
def bag_of_words(tokenized_words,words):
    tokenized_words = [stem(w) for w in tokenized_words]
    bag = np.zeros(len(words))
    for idx,w in enumeraten(words):
        if w in tokenized_words:
            bag[idx] = 1.0
    return bag

In [7]:
bag_of_words(['hi'],['hi','how','hi'])

In [8]:
def bag_of_words(tokenized_words,words):
    tokenized_words = [stem(w) for w in tokenized_words]
    bag = np.zeros(len(words))
    for idx,w in enumerate(words):
        if w in tokenized_words:
            bag[idx] = 1.0
    return bag

In [9]:
bag_of_words(['hi'],['hi','how','hi'])

array([1., 0., 1.])

In [10]:
data = pd.read_csv('./data.csv')

In [11]:
data

         id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this  # earthquake...       1  
1              Forest fire near La Ronge Sask .  Canada       1  
2     All residents asked to  ' shelter in place '  ...       1  
3     13,000 people receive  # wildfires evacuation ...       1  
4     Just got sent this photo from Ruby  # Alaska a...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609   @ Aria Ahrary  @ TheTawniest The out of contr...       1  
7610  M1 . 94  [ 01 :

In [12]:
X = data['text']

In [13]:
data

         id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this  # earthquake...       1  
1              Forest fire near La Ronge Sask .  Canada       1  
2     All residents asked to  ' shelter in place '  ...       1  
3     13,000 people receive  # wildfires evacuation ...       1  
4     Just got sent this photo from Ruby  # Alaska a...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609   @ Aria Ahrary  @ TheTawniest The out of contr...       1  
7610  M1 . 94  [ 01 :

In [14]:
y = data['target']

In [15]:
words = []
data = []
labels = {}
labels_r = {}
idx = 0

In [16]:
for label in y.tolist():
    if label not in list(labels.keys()):
        idx += 1
        labels[label] = idx
        labels_r[idx] = label

In [17]:
labels

{1: 1, 0: 2}

In [18]:
data = pd.read_csv('./data.csv')[:3250]

In [19]:
X = data['text']

In [20]:
data

        id   keyword          location  \
0        1       NaN               NaN   
1        4       NaN               NaN   
2        5       NaN               NaN   
3        6       NaN               NaN   
4        7       NaN               NaN   
...    ...       ...               ...   
3245  4664  engulfed  Fleet/Oxford, UK   
3246  4666  engulfed               NaN   
3247  4667  engulfed                UK   
3248  4669  engulfed           Bahrain   
3249  4670  engulfed          Coventry   

                                                   text  target  
0     Our Deeds are the Reason of this  # earthquake...       1  
1              Forest fire near La Ronge Sask .  Canada       1  
2     All residents asked to  ' shelter in place '  ...       1  
3     13,000 people receive  # wildfires evacuation ...       1  
4     Just got sent this photo from Ruby  # Alaska a...       1  
...                                                 ...     ...  
3245  just got engulfed in a car 

In [21]:
y = data['target']

In [22]:
words = []
data = []
labels = {}
labels_r = {}
idx = 0

In [23]:
for label in y.tolist():
    if label not in list(labels.keys()):
        idx += 1
        labels[label] = idx
        labels_r[idx] = label

In [24]:
labels

{1: 1, 0: 2}

In [25]:
data = pd.read_csv('./data.csv')[:3250].sample(frac=1)

In [26]:
X = data['text']

In [27]:
data

        id              keyword                location  \
2291  3286             demolish              London, UK   
3083  4425          electrocute                     NaN   
1454  2097             casualty   In @4SkinChan 's arms   
1693  2443              collide             Medford, NJ   
922   1335           blown%20up               801 SL,UT   
...    ...                  ...                     ...   
1345  1943  burning%20buildings  New Orleans ,Louisiana   
2573  3690              destroy                  Norway   
1524  2204         catastrophic                 Lurking   
698   1005              blazing                     NaN   
1176  1693    bridge%20collapse                  Boston   

                                                   text  target  
2291  The far right racist  # AvigdorLiberman calls ...       1  
3083  She says that she ' d love to come help but\nT...       0  
1454   @ reriellechan HE WAS THE LICH KING ' S FIRST...       1  
1693   # TheDoolingGroup 2 

In [28]:
y = data['target']

In [29]:
words = []
data = []
labels = {}
labels_r = {}
idx = 0

In [30]:
for label in y.tolist():
    if label not in list(labels.keys()):
        idx += 1
        labels[label] = idx
        labels_r[idx] = label

In [31]:
labels

{1: 1, 0: 2}

In [32]:
for X_batch,y_batch in tqdm(zip(X,y)):
    X_batch = tokenize(X_batch)
    new_Xb = []
    for Xb in X_batch:
        new_Xb.append(stem(Xb))
    words.extend(new_X)
    data.append([
        new_X,
        np.eye(labels[y_batch],len(labels))[labels[y_batch]-1]
    ])

In [33]:
for X_batch,y_batch in tqdm(zip(X,y)):
    X_batch = tokenize(X_batch)
    new_X = []
    for Xb in X_batch:
        new_X.append(stem(Xb))
    words.extend(new_X)
    data.append([
        new_X,
        np.eye(labels[y_batch],len(labels))[labels[y_batch]-1]
    ])

In [34]:
data[0]

[['the',
  'far',
  'right',
  'racist',
  '#',
  'avigdorliberman',
  'call',
  'for',
  'destruct',
  'of',
  '#',
  'susiya',
  '!',
  'previous',
  'he',
  'also',
  'call',
  'for',
  'behead',
  '!'],
 array([1., 0.])]

In [35]:
data[650]

[['@',
  'cllrraymogford',
  'inde',
  'ray',
  'devast',
  'would',
  'be',
  'far',
  'more',
  'comprehens',
  '#',
  'hiroshima'],
 array([1., 0.])]

In [36]:
data[654]

[['youth', 'electrocut', 'in', 'khulna', '|', 'via', '@', 'sharethi'],
 array([1., 0.])]

In [37]:
data[654]

[['youth', 'electrocut', 'in', 'khulna', '|', 'via', '@', 'sharethi'],
 array([1., 0.])]

In [38]:
data[69]

[['/',
  '/',
  'im',
  'gon',
  'na',
  'beat',
  'armageddon',
  'as',
  'hsu',
  'hao',
  '?',
  'just',
  'got',
  'a',
  'flawless',
  'on',
  'my',
  'first',
  'tri'],
 array([0., 1.])]

In [39]:
words = sorted(set(words))

In [40]:
np.random.shuffle(data)

In [41]:
X = []
y = []

In [42]:
for sentence,tag in tqdm(data):
    X.append(bag_of_words(sentence,words))
    y.append(tag)

In [43]:
X[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [44]:
y[0]

array([0., 1.])

In [45]:
X[50]

array([0., 0., 0., ..., 0., 0., 0.])

In [46]:
X[590]

array([0., 0., 0., ..., 0., 0., 0.])

In [47]:
X[590][5]

0.0

In [48]:
X[590][6]

0.0

In [49]:
X[590]

array([0., 0., 0., ..., 0., 0., 0.])

In [50]:
print(X[590])

In [51]:
for a in X[590]:
    print(a)

In [52]:
data[590][0]

['@',
 'kshllcenterpri1',
 '@',
 'progress4ohio',
 'burn',
 'down',
 'build',
 'what',
 'you',
 'mean',
 'like',
 'when',
 'you',
 'burnt',
 'down',
 'those',
 'black',
 'church',
 '?']

In [53]:
X[590]

array([0., 0., 0., ..., 0., 0., 0.])

In [54]:
y[0]

array([0., 1.])

In [55]:
from sklearn.model_selection import *
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.125,shuffle=False)
X_train = torch.from_numpy(np.array(X_train)).to(device).float()
y_train = torch.from_numpy(np.array(y_train)).to(device).float()
X_test = torch.from_numpy(np.array(X_test)).to(device).float()
y_test = torch.from_numpy(np.array(y_test)).to(device).float()

In [56]:
def get_loss(model,X,y,criterion):
    preds = model(X)
    loss = criterion(preds,y)
    return loss.item()

In [57]:
def get_accuracy(model,X,y):
    preds = model(X)
    correct = 0
    total = 0
    for pred,yb in zip(preds,y):
        pred = int(torch.argmax(pred))
        yb = int(torch.argmax(yb))
        if pred == yb:
            correct += 1
        total += 1
    acc = round(correct/total,3)*100

In [58]:
class Model(Module):
    def __init__(self):
        super().__init__()
        self.hidden = 512
        self.activation = ReLU()
        self.linear1 = Linear(len(words),self.hidden)
        self.linear2 = Linear(self.hidden,self.hidden)
        self.linear3 = Linear(self.hidden,len(labels))
    
    def forward(self,X):
        preds = self.linear1(X)
        preds = self.activation(self.linear2(preds))
        preds = self.linear3(preds)
        return preds

In [59]:
model = Model().to(device)
criterion = MSELoss()
optimizer = Adam(model.parameters(),lr=0.001)
epochs = 100
batch_size = 32

In [60]:
wandb.init(project=PROJECT_NAME,name='baseline')
for _ in tqdm(range(epochs)):
    for i in range(0,len(X_train),batch_size):
        X_batch = X_train[i:i+batch_size]
        y_batch = y_train[i:i+batch_size]
        preds = model(X_batch)
        loss = criterion(preds,y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    model.eval()
    torch.cuda.empty_cache()
    wandb.log({'Loss':(get_loss(model,X_train,y_train,criterion)+get_loss(model,X_batch,y_batch,criterion)/2)})
    torch.cuda.empty_cache()
    wandb.log({'Val Loss':get_loss(model,X_test,y_test,criterion)})
    torch.cuda.empty_cache()
    wandb.log({'Acc':(get_accuracy(model,X_train,y_train)+get_accuracy(model,X_batch,y_batch))/2})
    torch.cuda.empty_cache()
    wandb.log({'Val Acc':get_accuracy(model,X_test,y_test)})
    torch.cuda.empty_cache()
    model.train()
wandb.finish()

In [61]:
def get_accuracy(model,X,y):
    preds = model(X)
    correct = 0
    total = 0
    for pred,yb in zip(preds,y):
        pred = int(torch.argmax(pred))
        yb = int(torch.argmax(yb))
        if pred == yb:
            correct += 1
        total += 1
    acc = round(correct/total,3)*100
    return acc

In [62]:
class Model(Module):
    def __init__(self):
        super().__init__()
        self.hidden = 512
        self.activation = ReLU()
        self.linear1 = Linear(len(words),self.hidden)
        self.linear2 = Linear(self.hidden,self.hidden)
        self.linear3 = Linear(self.hidden,len(labels))
    
    def forward(self,X):
        preds = self.linear1(X)
        preds = self.activation(self.linear2(preds))
        preds = self.linear3(preds)
        return preds

In [63]:
model = Model().to(device)
criterion = MSELoss()
optimizer = Adam(model.parameters(),lr=0.001)
epochs = 100
batch_size = 32

In [64]:
wandb.init(project=PROJECT_NAME,name='baseline')
for _ in tqdm(range(epochs)):
    for i in range(0,len(X_train),batch_size):
        X_batch = X_train[i:i+batch_size]
        y_batch = y_train[i:i+batch_size]
        preds = model(X_batch)
        loss = criterion(preds,y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    model.eval()
    torch.cuda.empty_cache()
    wandb.log({'Loss':(get_loss(model,X_train,y_train,criterion)+get_loss(model,X_batch,y_batch,criterion)/2)})
    torch.cuda.empty_cache()
    wandb.log({'Val Loss':get_loss(model,X_test,y_test,criterion)})
    torch.cuda.empty_cache()
    wandb.log({'Acc':(get_accuracy(model,X_train,y_train)+get_accuracy(model,X_batch,y_batch))/2})
    torch.cuda.empty_cache()
    wandb.log({'Val Acc':get_accuracy(model,X_test,y_test)})
    torch.cuda.empty_cache()
    model.train()
wandb.finish()